(defun get-permutation (n k)
  (let ((numbers (loop for i from 1 to n collect i))
        (k (1- k)))
    (with-output-to-string (res)
      (loop while (>= k 0)
         do (multiple-value-bind
                  (q r)
                (floor k (reduce #'* (loop for i from 1 below (length numbers)
                                        collect i)))
              (format res "~a" (nth q numbers))
              (when (zerop r)
                (return (format res "~{~a~}" (remove (nth q numbers) numbers))))
              (setf k r)
              (setf numbers (remove (nth q numbers) numbers))))
      res)))